<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="level_tiles" tilewidth="16" tileheight="16" tilecount="64" columns="8">
 <image source="../graphics/level_tiles.png" width="128" height="128"/>
 <tile id="0" type="wall"/>
 <tile id="1" type="wall"/>
 <tile id="2" type="wall"/>
 <tile id="3" type="wall"/>
 <tile id="4" type="wall"/>
 <tile id="5" type="wall"/>
 <tile id="6" type="wall"/>
 <tile id="7" type="wall"/>
 <tile id="8" type="wall"/>
 <tile id="9" type="floor"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="13" type="wall"/>
 <tile id="14" type="wall"/>
 <tile id="15" type="wall"/>
 <tile id="16" type="wall"/>
 <tile id="17" type="wall"/>
 <tile id="18" type="wall"/>
 <tile id="19" type="wall"/>
 <tile id="20" type="wall"/>
 <tile id="21" type="wall"/>
 <tile id="22" type="wall"/>
 <tile id="23" type="wall"/>
 <tile id="24" type="goal"/>
 <tile id="25" type="box"/>
 <tile id="26" type="box"/>
 <tile id="27" type="wall"/>
 <tile id="28" type="wall"/>
 <tile id="29" type="wall"/>
 <tile id="30" type="wall"/>
 <tile id="31" type="wall"/>
 <tile id="32" type="door"/>
 <tile id="33" type="door"/>
 <tile id="34" type="door"/>
 <tile id="35" type="door"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="wall"/>
 <tile id="38" type="wall"/>
 <tile id="40" type="door"/>
 <tile id="41" type="door"/>
 <tile id="42" type="door"/>
 <tile id="43" type="door"/>
</tileset>
